apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-webapp
  labels:
    app: k8s-webapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: k8s-webapp
  template:
    metadata:
      labels:
        app: k8s-webapp
    spec:
      containers:
      - name: k8s-webapp
        image: rohitmakwana/k8swebapp
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-webapp-final
spec:
  type: NodePort
  selector:
    app: k8s-webapp
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30003
  externalIPs:
    - 13.233.195.27